# Generated by Django 3.1.5 on 2021-06-24 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, null=True, unique=True)),
                ('rubrique', models.CharField(blank=True, max_length=100, null=True)),
                ('type_compte', models.CharField(max_length=50)),
                ('reseau_compte', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monnaie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_monnaie', models.CharField(blank=True, max_length=3, null=True)),
                ('lib_monnaie', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pos1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, unique=True)),
                ('lib', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, unique=True)),
                ('lib', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.pos1')),
            ],
        ),
        migrations.CreateModel(
            name='Pos3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, unique=True)),
                ('lib', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.pos2')),
            ],
        ),
        migrations.CreateModel(
            name='Pos6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, unique=True)),
                ('lib', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.pos3')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_user', models.CharField(blank=True, max_length=100, null=True)),
                ('type_user', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='unite_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unite', models.CharField(blank=True, max_length=50, null=True)),
                ('reseau', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('commeriale', models.CharField(blank=True, max_length=1, null=True)),
                ('etranger', models.CharField(blank=True, max_length=1, null=True)),
                ('tresorie', models.CharField(blank=True, max_length=1, null=True)),
                ('Trafic_Indicateur', models.CharField(blank=True, max_length=1, null=True)),
                ('Emission_Indicateur', models.CharField(blank=True, max_length=1, null=True)),
                ('Recette_Indicateur', models.CharField(blank=True, max_length=1, null=True)),
                ('Exploitation_Indicateur', models.CharField(blank=True, max_length=1, null=True)),
                ('lib_monnaie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.monnaie')),
                ('pro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.profile')),
            ],
        ),
        migrations.CreateModel(
            name='trafic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('annuel', models.FloatField(blank=True, null=True)),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
        migrations.CreateModel(
            name='taux_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taux', models.FloatField(blank=True, null=True)),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('code_moneeée', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.monnaie')),
            ],
        ),
        migrations.CreateModel(
            name='recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('annuel', models.FloatField(blank=True, null=True)),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
        migrations.CreateModel(
            name='Pos7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scf', models.IntegerField(blank=True, unique=True)),
                ('lib', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.pos6')),
            ],
        ),
        migrations.CreateModel(
            name='entete_pv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('unite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
        migrations.CreateModel(
            name='emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('annuel', models.FloatField(blank=True, null=True)),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
        migrations.CreateModel(
            name='depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('annuel', models.FloatField(blank=True, null=True)),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
    ]
