# Generated by Django 3.1.5 on 2021-06-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0002_auto_20210624_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entete_pv',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entete_pv',
            name='unite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1'),
        ),
    ]
