# Generated by Django 3.1.5 on 2021-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0004_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='type1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
