# Generated by Django 3.1.5 on 2021-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0007_auto_20210625_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='rempli',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
