# Generated by Django 3.1.5 on 2021-06-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0008_proposition_rempli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='calcul',
        ),
    ]
