# Generated by Django 3.1.5 on 2021-06-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0010_controle_budgetaire_entete_controle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='controle_budgetaire',
        ),
    ]
