# Generated by Django 3.1.5 on 2021-06-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0013_controle_khra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='controle_khra',
            new_name='controle_bud',
        ),
    ]
