# Generated by Django 3.1.5 on 2021-06-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0014_auto_20210628_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='type',
            new_name='type2',
        ),
        migrations.DeleteModel(
            name='controle_budgetaire',
        ),
    ]
