# Generated by Django 3.1.5 on 2021-06-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0015_auto_20210629_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='type2',
            new_name='type',
        ),
    ]
