# Generated by Django 3.1.5 on 2021-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0017_reunion_bud'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='cloture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='prevision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
