# Generated by Django 3.1.5 on 2021-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0018_auto_20210629_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion_bud',
            name='controle_budgetaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
