# Generated by Django 3.1.5 on 2021-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0024_auto_20210630_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion_bud',
            name='cadre',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reunion_bud',
            name='cdd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reunion_bud',
            name='sd',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
