# Generated by Django 3.1.5 on 2021-06-30 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0025_auto_20210630_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion_bud',
            name='cadre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre', to='cadre_bud.profile'),
        ),
        migrations.AlterField(
            model_name='reunion_bud',
            name='cdd',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd', to='cadre_bud.profile'),
        ),
        migrations.AlterField(
            model_name='reunion_bud',
            name='sd',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='cadre_bud.profile'),
        ),
    ]
