# Generated by Django 3.1.5 on 2021-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0026_auto_20210630_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='cadre1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
