# Generated by Django 3.1.5 on 2021-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0027_reunion_bud_cadre1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='rempli',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
