# Generated by Django 3.1.5 on 2021-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0028_auto_20210630_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle_bud',
            name='rempli',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
