# Generated by Django 3.1.4 on 2021-07-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0031_entete_realisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='sd',
        ),
        migrations.DeleteModel(
            name='entete_realisation',
        ),
        migrations.DeleteModel(
            name='realisation',
        ),
    ]
