# Generated by Django 3.1.4 on 2021-07-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0033_entete_realisation_realisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='entete_realisation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('unite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1')),
            ],
        ),
        migrations.CreateModel(
            name='realisation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('realisation', models.FloatField(blank=True, null=True)),
                ('type1', models.CharField(blank=True, max_length=20, null=True)),
                ('scf', models.IntegerField(blank=True, null=True)),
                ('rempli', models.BooleanField(blank=True, default=False)),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_realisation2')),
            ],
        ),
    ]
