# Generated by Django 3.1.4 on 2021-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0034_entete_realisation2_realisation2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='pv',
        ),
        migrations.DeleteModel(
            name='entete_realisation',
        ),
        migrations.DeleteModel(
            name='realisation',
        ),
    ]
