# Generated by Django 3.1.4 on 2021-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0035_auto_20210715_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
