# Generated by Django 3.1.4 on 2021-07-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0036_reunion_bud_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='realisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.realisation2'),
        ),
    ]
