# Generated by Django 3.1.4 on 2021-07-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0037_reunion_bud_realisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion_bud',
            name='realisation',
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='realisation_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='realisation_1', to='cadre_bud.realisation2'),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='realisation_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='realisation_2', to='cadre_bud.realisation2'),
        ),
    ]
