# Generated by Django 3.1.4 on 2021-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0038_auto_20210718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion_bud',
            name='realisation_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reunion_bud',
            name='realisation_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
