# Generated by Django 3.1.4 on 2021-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0039_auto_20210718_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion_bud',
            name='proposition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
