# Generated by Django 3.1.4 on 2021-07-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0040_auto_20210718_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv'),
        ),
    ]
