# Generated by Django 3.1.4 on 2021-07-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0044_unite_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unite_1',
            name='pro',
        ),
    ]
