# Generated by Django 3.1.4 on 2021-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0046_unite_pos6'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='monnie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='regler_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite_pos6',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
