# Generated by Django 3.1.4 on 2021-07-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0048_auto_20210724_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation2',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv'),
        ),
    ]
