# Generated by Django 3.1.4 on 2021-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0049_auto_20210724_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation2',
            name='ajouter_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='date_ajout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='date_modif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='modifier_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='monnie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='regler_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
