# Generated by Django 3.1.4 on 2021-07-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0051_historique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='date_ajout',
            new_name='date_h',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='date_modif',
        ),
    ]
