# Generated by Django 3.1.4 on 2021-07-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0052_auto_20210725_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='ajouter_par',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='date_modif',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='modifier_par',
        ),
    ]
