# Generated by Django 3.1.4 on 2021-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0054_auto_20210725_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='cdd1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='date1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='date2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='date3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reunion_bud',
            name='sd1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
