# Generated by Django 3.1.4 on 2021-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0055_auto_20210725_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion_bud',
            name='is_valide',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
