# Generated by Django 3.1.4 on 2021-07-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0056_reunion_bud_is_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation2',
            name='cadre1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='cdd1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='realisation2',
            name='sd1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
