# Generated by Django 3.1.4 on 2021-07-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0057_auto_20210726_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisation2',
            old_name='cadre1',
            new_name='cdd',
        ),
        migrations.RemoveField(
            model_name='realisation2',
            name='cdd1',
        ),
        migrations.RemoveField(
            model_name='realisation2',
            name='sd1',
        ),
    ]
