# Generated by Django 3.1.4 on 2021-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0058_auto_20210726_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifie_bud',
            name='cdd1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='date1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='date2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='date3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='is_valide',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='sd1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
