# Generated by Django 3.1.4 on 2021-07-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0060_modification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modification',
            old_name='modification',
            new_name='modif',
        ),
        migrations.AddField(
            model_name='notifie_bud',
            name='modification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='cadre_bud.modification'),
        ),
    ]
