# Generated by Django 3.1.4 on 2021-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0062_auto_20210728_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='cdd1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='modification',
            name='sd1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
