# Generated by Django 3.1.4 on 2021-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0065_auto_20210728_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='notifie',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
