# Generated by Django 3.2.5 on 2021-08-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0066_auto_20210729_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='entete_pv',
            name='rempli',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
