# Generated by Django 3.2.5 on 2021-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0067_entete_pv_rempli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifie_bud_m',
            old_name='prevision',
            new_name='aout',
        ),
        migrations.RemoveField(
            model_name='notifie_bud_m',
            name='mois',
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='avril',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='decembre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='fevrier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='janvier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='juillet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='juin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='mars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='novembre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='octobre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='septembre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
