# Generated by Django 3.2.5 on 2021-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0068_auto_20210808_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifie_bud_m',
            name='cdd1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notifie_bud_m',
            name='sd1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
