# Generated by Django 3.2.5 on 2021-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0069_auto_20210808_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifie_bud_m',
            name='is_valide',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
