# Generated by Django 3.2.2 on 2021-08-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0070_notifie_bud_m_is_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='aout',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='avril',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='decembre',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='fevrier',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='janvier',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='juillet',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='juin',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='mai',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='mars',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='novembre',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='octobre',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='septembre',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifie_bud_m',
            name='type',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
