# Generated by Django 3.2.2 on 2021-08-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0071_auto_20210814_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='modification_mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=0, max_length=20)),
                ('type_modif', models.CharField(blank=True, max_length=20, null=True)),
                ('rubrique', models.CharField(blank=True, max_length=20, null=True)),
                ('janvier', models.FloatField(blank=True, default=0)),
                ('fevrier', models.FloatField(blank=True, default=0)),
                ('mars', models.FloatField(blank=True, default=0)),
                ('avril', models.FloatField(blank=True, default=0)),
                ('mai', models.FloatField(blank=True, default=0)),
                ('juin', models.FloatField(blank=True, default=0)),
                ('juillet', models.FloatField(blank=True, default=0)),
                ('aout', models.FloatField(blank=True, default=0)),
                ('septembre', models.FloatField(blank=True, default=0)),
                ('octobre', models.FloatField(blank=True, default=0)),
                ('novembre', models.FloatField(blank=True, default=0)),
                ('decembre', models.FloatField(blank=True, default=0)),
                ('cadre1', models.BooleanField(blank=True, default=False)),
                ('cdd1', models.BooleanField(blank=True, default=False)),
                ('sd1', models.BooleanField(blank=True, default=False)),
                ('is_valide', models.BooleanField(blank=True, default=False)),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre222', to='cadre_bud.profile')),
                ('cdd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdd222', to='cadre_bud.profile')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv')),
                ('sd', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd222', to='cadre_bud.profile')),
            ],
        ),
    ]
