# Generated by Django 3.2.2 on 2021-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0072_modification_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entete_pv',
            name='etat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
