# Generated by Django 3.2.2 on 2021-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0073_entete_pv_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='runion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entete_pv',
            name='etat',
        ),
    ]
