# Generated by Django 3.2.7 on 2021-09-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0074_auto_20210823_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle_bud',
            name='ec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv'),
        ),
    ]
