# Generated by Django 3.2.7 on 2021-09-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0075_alter_controle_bud_ec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entete_controle',
        ),
    ]
