# Generated by Django 3.2.7 on 2021-09-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0076_delete_entete_controle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emission',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='pv',
        ),
        migrations.AddField(
            model_name='proposition',
            name='annuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='mois',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1'),
        ),
        migrations.DeleteModel(
            name='depense',
        ),
        migrations.DeleteModel(
            name='emission',
        ),
        migrations.DeleteModel(
            name='recette',
        ),
    ]
