# Generated by Django 3.2.7 on 2021-09-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0077_auto_20210901_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='annuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='mois',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.unite_1'),
        ),
        migrations.AddField(
            model_name='historique',
            name='rubrique',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='trafic',
        ),
    ]
