# Generated by Django 3.2.7 on 2021-09-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0078_auto_20210901_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='annuel',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='montant',
        ),
        migrations.AlterField(
            model_name='proposition',
            name='pv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv'),
        ),
    ]
