# Generated by Django 3.2.7 on 2021-09-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0079_auto_20210906_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification_mm',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='modification_mm',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='modification_mm',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='modification_mm',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='annuel',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='rubrique',
        ),
        migrations.DeleteModel(
            name='entete_realisation2',
        ),
        migrations.DeleteModel(
            name='modification_mm',
        ),
    ]
