# Generated by Django 3.2.7 on 2021-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0080_auto_20210907_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='commentaire_degre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
