# Generated by Django 3.2.7 on 2021-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0081_proposition_commentaire_degre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite_pos6',
            name='added_by',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
