# Generated by Django 3.2.7 on 2021-09-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0082_unite_pos6_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cadre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadre5', to='cadre_bud.profile')),
                ('notified_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.profile')),
                ('pv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadre_bud.entete_pv')),
            ],
        ),
    ]
