# Generated by Django 3.2.7 on 2021-09-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadre_bud', '0083_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='cadre',
            new_name='modifier_user',
        ),
    ]
